### ISSUE TITLE
does not work on macOS

### ISSUE THREAD

**Issue by grylem** [rillig/checkperms#1]
compile
make test elf, macho, sh files - chmod 644

find * -print | ./checkperms -c
nothing
chmod 755 README
find * -print | ./checkperms -c
and now
warning: README: executable bit is set on non-executable file.
0 errors and 1 warnings.
but no warnings for elf, macho, sh files
Please fix it
Thanks.

**Comment by rillig** [comment]
I'm not sure I understand what exactly you expect. ELF files are executable, therefore these may have the executable bit set. Could you explain _why_ checkperms should issue a warning for these files?

By the way, "does not work" is a terrible description for any bug. Simon Tatham has [written a nice document that explains it in much detail](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by grylem** [comment]
Sorry.
prepare files to testing
1. elf binary with name "elf"(ELF 64-bit)
2. mach-o binary with name "macho"(Mach-O 64-bit)
chmod 644 elf macho - now binaries dont have executable flag.
theoretically checkperms should show me that my binaries(elf and macho) dont have executable flag
in the folder that contains elf and macho
find * -print | checkperms -c
no any warnings
Regards.

**Comment by rillig** [comment]
Ah, now I understand.

The original purpose of checkperms was to get correct file permissions in [pkgsrc](https://www.pkgsrc.org/). It often happened that .zip files were produced on Windows or DOS, or from Samba shares and therefore had the executable bit set on files where it doesn't make sense.

And even if a file starts with `\177ELF`, this doesn't mean the file should be executable. If it's a shared library, on many systems a simple 444 is enough, there's no need for 555.

What you describe is the other way round. Having files that should/might be executable but really aren't. I didn't stumble upon such a case in the recent years and therefore didn't implement it. And as I described in the paragraph above, drawing the line is not always simple.

Therefore I'd rather not change anything right now. Maybe you could describe your actual use case so that I know _why_ you have these executable files without the x bit set, and where you got them from.

**Comment by grylem** [comment]
I have some 7z archive with *.dylib etc. Files archived without right permissions.
Maybe you can also add option like - dont fix perms for bash/sh scripts? it is not critical but useful.
Now checkperms set 644 for *.sh and shell scripts without extension.
Anyway thanks for the great tool.

**Comment by rillig** [comment]
A quick workaround for your case would be to `chmod -R ugo+x .` and then run checkperms.

You said that checkperms "fixes" the executable bit in a shell script. This means that the shell script doesn't start with a `#!` line. In modern times, almost all shell scripts do so, therefore I implemented it that way.

If the file doesn't start with a `#!` line, it could also be a plain text file. Detecting whether a plain text file is a shell script or not is too difficult for checkperms. It would require lots of guessing. Therefore I didn't do that.

A general note: when you report something that doesn't work as you expect, please provide more details than you do now. In the second paragraph above, I had to guess what your situation is. Maybe I got it right, maybe I didn't, I cannot be sure. Did you already read the document I suggested?

**Comment by grylem** [comment]
> A quick workaround for your case would be to chmod -R ugo+x . and then run checkperms.

I know this way :)

>If the file doesn't start with a #! line, it could also be a plain text file. Detecting whether a plain text file is a shell script or not is too difficult for checkperms. It would require lots of guessing. Therefore I didn't do that.

I understand

> Did you already read the document I suggested?

Yes, thanks for the advice and understanding
